# Generated by Django 3.1.5 on 2025-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='selenium',
            field=models.BooleanField(default=False),
        ),
    ]
