# Generated by Django 3.1.5 on 2022-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('title', models.CharField(max_length=20)),
                ('cover', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
