# Generated by Django 3.1.5 on 2025-11-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_selenium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='selenium',
        ),
    ]
