# Generated by Django 3.1.5 on 2022-05-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
