# Generated by Django 3.1.5 on 2022-05-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220523_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='url',
            new_name='feed_url',
        ),
    ]
