# Generated by Django 3.2.25 on 2026-08-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='scrape_type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('RSS', 'RSS'), ('WORDPRESS_API', 'WordPress API')], default='HTML', max_length=20),
        ),
    ]
