# Generated by Django 3.2.25 on 2026-08-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_function_news_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='state',
            field=models.CharField(default='NM', max_length=2),
        ),
    ]
