# Generated by Django 3.1.5 on 2022-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='function',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
