# Generated by Django 2.1 on 2022-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_cities_counties_news_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Counties',
                'db_table': 'county',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='images/')),
                ('feed_url', models.URLField()),
                ('city', models.CharField(choices=[('Albuquerque', 'Albuquerque'), ('Alamagordo', 'Alamagordo'), ('Artesia', 'Artesia'), ('Belen', 'Belen'), ('Carlsbad', 'Carlsbad'), ('Clovis', 'Clovis'), ('Gallup', 'Gallup'), ('Grants', 'Grants'), ('Edgewood', 'Edgewood'), ('Espanola', 'Espanola'), ('Farmington', 'Farmington'), ('Gallup', 'Gallup'), ('Hobbs', 'Hobbs'), ('Las Cruces', 'Las Cruces'), ('Las Vegas', 'Las Vegas'), ('Los Alamos', 'Los Alamos'), ('Portales', 'Portales'), ('Rio Rancho', 'Rio Rancho'), ('Roswell', 'Roswell'), ('Santa Fe', 'Santa Fe'), ('Silver City', 'Silver City'), ('Socorro', 'Socorro'), ('Taos', 'Taos')], max_length=20)),
                ('county', models.CharField(choices=[('Bernalillo', 'Bernalillo'), ('Sandoval', 'Sandoval'), ('Dona Anna', 'Dona Anna')], max_length=20)),
                ('region', models.CharField(choices=[('Albuquerque', 'Albuquerque'), ('New Mexico', 'New Mexico'), ('Politics', 'Politics'), ('Northern', 'Northern'), ('Central', 'Central'), ('Southern', 'Southern'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Northwestern', 'Northwestern'), ('Northeastern', 'Northeastern'), ('Southern', 'Southern'), ('Southwestern', 'Southwestern'), ('Southeastern', 'Southeastern')], max_length=20)),
                ('function', models.CharField(max_length=20)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'New',
                'db_table': 'news',
            },
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
