# Generated by Django 3.1.5 on 2022-05-21 03:23

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='wallpapers/', verbose_name='Image')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
        ),
    ]
