# Generated by Django 3.1.5 on 2022-07-15 01:51

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='wallpapers/'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
