# Generated by Django 3.1.7 on 2022-03-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image', models.ImageField(upload_to='wallpapers', verbose_name='Image')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
        ),
        migrations.DeleteModel(
            name='Background',
        ),
    ]
