# Generated by Django 3.1.7 on 2022-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=False, upload_to='images/'),
            preserve_default=False,
        ),
    ]
